language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng lint
  - ng build --prod --base-href https://ferozalizada.github.io/https://github.com/professor-forward/csi3140-winter2020-project-csi3140_project_alizada/
