version: "3.0" # specify docker-compose version

# Define the services/ containers to be run
services:
  angular: # name of the first service
    build: MusiQ # specify the directory of the Dockerfile
    ports:
      - "4200:4200" # specify port mapping
    container_name: frontend
    restart: always

  express: # name of the second service
    build: backend/src # specify the directory of the Dockerfile
    ports:
      - "8083:8083" #specify ports mapping
    container_name: backend
    restart: always
    links:
      - database # link this service to the database service

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
